title: JSON Schema Everywhere
description: Schema validation for data description languages
github_username: json-schema-everywhere
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE.txt
  - _languages/cson.md
  - _languages/json.md
collections:
  languages:
    output: true
    permalink: '/:path'

defaults:
  - scope:
      path: ''
      type: languages
    values:
      layout: language