title: JSON Schema Everywhere
description: Schema validation for data description languages
github_username: json-schema-everywhere
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE.txt